name: docker-images

on:
  push:
    paths:
    - 'docker-makepkg/**'
    branches: 
    - master
  pull_request:
    branches: 
    - master
  # Allow manual trigger as well
  workflow_dispatch:
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        image: 
          - docker-makepkg
        include:
          - image: docker-makepkg
            add_tag: true

    runs-on: ubuntu-latest
    steps:
      - 
        name: Determin docker tag
        env:
          TAG_NAME: ${{ github.ref }}
        run: |
          if [ "${TAG_NAME##*/}" = "master" ]; then
            tag=latest
          else
            tag=build-test
          fi
          echo "docker_tag=${tag}" >> $GITHUB_ENV
      - 
        name: Determin dockerfile
        env:
          DF: ${{ matrix.dockerfile }}
          IMG: ${{ matrix.image }}
        run: |
          if [ -z "${DF}" ]; then
            DF="${IMG}"
          fi
          echo "docker_file=${DF}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4.2.2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: amd64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      -
        name: Cache Docker layers
        uses: actions/cache@v4.1.2
        if: github.event_name == 'push'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.image }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.image }}-
      -
        name: Cache Docker layers
        uses: actions/cache@v4.1.2
        if: github.event_name == 'pull_request'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-pr-${{ github.event.pull_request.head.user.login }}-buildx-${{ matrix.image }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pr-${{ github.event.pull_request.head.user.login }}-buildx-${{ matrix.image }}-
            ${{ runner.os }}-buildx-${{ matrix.image }}-
      -
        name: Cache Docker layers
        if: github.event_name != 'push' && github.event_name != 'pull_request'
        run: |
          echo "I do not know how to setup cache"
          exit -1
      -
        name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        if: github.event_name == 'push'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: ${{ env.docker_file }}/
          file: ${{ env.docker_file }}/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' }}
          tags: nullx47/${{ matrix.image }}:${{ env.docker_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
